:{sel=SELECT VERSION , LOCKSTATUS FROM SYS_LOCK WHERE LOCKNAME = ? };
:{ins=INSERT INTO SYS_LOCK ( LOCKNAME , VERSION , LOCKSTATUS ) VALUES ( ? , ? , ? )};
:{upd=UPDATE SYS_LOCK SET VERSION = ? , LOCKSTATUS = ?  WHERE LOCKNAME = ?  AND  VERSION = ? };